name: portfolio
description: This my portfolio develop by flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  font_awesome_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

fonts:
  - family: MaterialIcons
    fonts:
      - asset: web/assets/fonts/MaterialIcons-Regular.ttf
  - family: Quicksand
    fonts:
      - asset: web/assets/fonts/Quicksand-Regular.otf
  - family: ProductSans
    fonts:
      - asset: web/assets/fonts/Product-Sans-Regular.ttf
  - family: NexaBold
    fonts:
      - asset: web/assets/fonts/Nexa-Bold.otf
  - family: NexaLight
    fonts:
      - asset: web/assets/fonts/Nexa-Light.otf